---

switches:
  hosts:
    switch:
      ansible_host: 172.16.0.73
      ansible_network_os: cisco.ios.ios
      ansible_user: ansible_poc
routers:
  hosts:
    router:
      ansible_host: 172.16.0.74
      ansible_network_os: cisco.ios.ios
      ansible_user: ansible_poc
network:
  children:
    switches:
    routers:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: ansible_poc
    ansible_password: Q22!@h!JT
    ansible_become: yes
    ansible_become_method: enable
    

